version: '3.8'

services:
  web:
    build: .
    command: gunicorn trees_project.wsgi -b 0.0.0.0:8000
    environment:
      - ENVIRONMENT=production
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=0
      - ALLOWED_HOSTS=trees-production.up.railway.app
      - DATABASE_URL=${DATABASE_URL}
      - STRIPE_TEST_PUBLISHABLE_KEY=${STRIPE_TEST_PUBLISHABLE_KEY}
      - STRIPE_TEST_SECRET_KEY=${STRIPE_TEST_SECRET_KEY}
    volumes:
      - .:/Trees
    ports:
      - "${PORT:-8000}:8000"
    depends_on:
      - db
  
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
