# Generated by Django 5.1.6 on 2025-02-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book',
            new_name='tree',
        ),
    ]
