# Generated by Django 5.1.6 on 2025-02-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0004_rename_author_review_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
