# Generated by Django 5.1.6 on 2025-02-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0005_tree_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
