# Generated by Django 5.1.6 on 2025-02-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0006_alter_tree_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tree',
            options={'permissions': [('special_status', 'Can see all trees')]},
        ),
    ]
